version: "3.8"

services:
  react:
    container_name: sabad_front
    image: sabad_front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000